FROM node:22-slim AS builder

WORKDIR /app

COPY client/package.json client/package-lock.json /app/
RUN npm ci

COPY client /app/

RUN npm run build


FROM nginx:alpine AS production


COPY --from=builder /app/dist /usr/share/nginx/html

# Opcional: reemplaza el default.conf si necesitas configuraciones personalizadas
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
