
services:
  frontend:
    build:
      context: .
      dockerfile: client/dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
  
  backend:
    build:
      context: .
      dockerfile: server/dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./server:/app

networks:
  app-network:
    driver: bridge

