
services:
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
  
  backend:
    build:
      context: .
      dockerfile: server/dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    networks:
      - app-network
    volumes:
      - ./model:/app/model
      - ./data:/app/data

networks:
  app-network:
    driver: bridge

