ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-slim

WORKDIR /app


COPY requirements.txt .


RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt


COPY server /app/


EXPOSE 8000


CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]